spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    alicloud:
#      access-key: LTAI5tEqbcuPVUupC6jeYZP4
#      secret-key: jyfrI6iZmfEKhII3pXqrVqFF7oaSox
#      oss:
#        endpoint: oss-cn-shanghai.aliyuncs.com

  application:
    name: chenfengmall-third-party

server:
  port: 30000